-- Create tables section -------------------------------------------------

-- Table DIM_CIDADAO

CREATE TABLE DIM_CIDADAO(
  RA double(12,0),
  MUNICIPIO_NASCIMENTO_COD double(8,0),
  PAIS_NASCIMENTO_COD double(4,0),
  ESTADO_CIVIL_COD double(1,0),
  ESTADO_CIVIL_DESC Varchar(30 ),
  SEXO_SG Char(1 ),
  ESCOLAR_COD_SEQ double,
  OCUPACAO_COD Varchar(5 ),
  SITUACAO_MILITAR_COD double(2,0),
  VINCULACAO_ANO double(4,0),
  ATUALIZACAO_DATA Date,
  ZONA_RESIDENCIAL_COD double(2,0),
  MUNICIPIO_RESIDENCIAL_COD double(8,0),
  PAIS_RESIDENCIA_COD double(4,0),
  CSM_COD double(2,0),
  JSM_COD double(3,0),
  DISPENSA_INCORP_COD double(2,0),
  TIPO_SANGUINEO Varchar(2 ),
  FATOR_RH Varchar(13 ),
  PESO double(3,0),
  ALTURA double(3,0),
  FORCA_MUSCULAR double(3,0),
  CABECA double(2,0),
  CALCADO_NR double(2,0),
  CINTURA_NR double(3,0),
  UNIFORME_NR Varchar(2 ),
  ACUIDADE_VISUAL_DESC Varchar(13 ),
  ACUIDADE_AUDITIVA_DESC Varchar(13 ),
  FORCA_DESEJA_SERVIR_COD double(2,0),
  SABE_NADAR_ST Char(1 ),
  CSE_INDICACAO_COD double(2,0),
  CSE_RESULTADO_COD double(2,0),
  GEOGRAFIA_COD_SEQ double,
  GRUPAM_INCORP_COD Varchar(1 ),
  PADRAO_CODIGO Varchar(3 ),
  TIPO_DISTRIBUICAO_COD double(2,0),
  NIVEL_AJUSTAMENTO_COD double(2,0),
  GRUPO_DISTRIB_COD double(2,0),
  DISTR_ORDEM_NR double(6,0),
  POSTO_GRAD_COD_SEQ double,
  QM_CODIGO Varchar(4 ),
  CARGO_MILITAR_CODIGO Varchar(4 ),
  QCP_FRACAO_ID Varchar(15 ),
  SITUACAO_MOB_COD double(2,0),
  DESTINO_MOB_COD double(2,0),
  CLASSE_RESERVA_COD double(2,0),
  COMPORTAMENTO_COD double(2,0),
  FORCA_MILITAR_COD double(2,0)
);


-- Create indexes for table DIM_CIDADAO

CREATE INDEX CIDADADAO_SIT_MILITAR_IDX ON DIM_CIDADAO (SITUACAO_MILITAR_COD)
;

-- Add keys for table DIM_CIDADAO

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT DIM_CIDADAO_PK PRIMARY KEY (RA)
;
  
-- Table FATO_EVENTO_CIDADAO

CREATE TABLE FATO_EVENTO_CIDADAO(
  CIDADAO_RA Double(12,0),
  EVENTO_SERMIL_COD Double(2,0),
  DT_EVENTO Date,
  CSM_COD Double(2,0),
  JSM_COD Double(3,0),
  GEOGRAFIA_COD_SEQ Double,
  CIDADAO_IDADE Double(6,3),
  ALTURA Double(3,0),
  ST_ADIAMENTO Char(1 ),
  TEMPO_COD_SEQ Double NOT NULL,
  ANO_REFERENCIA Double NOT NULL
);


-- Create indexes for table FATO_EVENTO_CIDADAO

CREATE INDEX EVENT_GEOFRAFIA_IDX ON FATO_EVENTO_CIDADAO (GEOGRAFIA_COD_SEQ)
;

CREATE INDEX EVENT_JSM_IDX ON FATO_EVENTO_CIDADAO (CSM_COD,JSM_COD)
;

CREATE INDEX EVENTO_SERMIL_IDX ON FATO_EVENTO_CIDADAO (EVENTO_SERMIL_COD)
;

CREATE INDEX EVENT_DT_EVENT_IDX ON FATO_EVENTO_CIDADAO (DT_EVENTO)
;

-- Add keys for table FATO_EVENTO_CIDADAO

ALTER TABLE FATO_EVENTO_CIDADAO ADD CONSTRAINT FATO_EVENTO_CIDADAO_PK PRIMARY KEY (CIDADAO_RA,EVENTO_SERMIL_COD,DT_EVENTO,TEMPO_COD_SEQ)
;


-- Table DIM_GEOGRAFIA

CREATE TABLE DIM_GEOGRAFIA(
  GEOGRAFIA_COD_SEQ Double NOT NULL,
  OM_DATA_EXTINCAO Date,
  OM_CODIGO_GUA Double(9,0) NOT NULL,
  OM_SUBTIPO Varchar(20 ),
  RM_SIGLA Varchar(30 ),
  OM_VM_BDA_SIGLA Varchar(30 ),
  OM_SITUACAO Char(1 ),
  OM_SIGLA Varchar(30 ),
  PAIS_NOME Varchar(30 ),
  OM_PRIO Char(1 ),
  COMIL_A_DESCRICAO Varchar(80 ),
  OM_ORIGEM Varchar(20 ),
  PAIS_IPC Varchar(1 ),
  OM_TIPO_OP Varchar(70 ),
  OM_VM_SUBORDINADA_SIGLA Varchar(30 ),
  RM_DESCRICAO Varchar(70 ),
  OM_VM_RM_ORGAO_CODIGO Varchar(6 ),
  OM_DATA_CRIACAO Date,
  CIDADE_SIGLA Varchar(5 ),
  OM_TIPO Varchar(20 ),
  CIDADE_UF_COD Double(3,0),
  OM_CODOM Varchar(6 ),
  OM_VM_BDA_DESC Varchar(70 ),
  OM_VM_SUBORDINADA Varchar(70 ),
  UF_DESCRICAO Varchar(50 ),
  OM_NOME Varchar(70 ),
  CIDADE_TIPO_LOCAL Varchar(1 ),
  UF_SIGLA Varchar(2 ),
  OM_VM_DE_SIGLA Varchar(30 ),
  CIDADE_IBGE_MUNICIPIO_COD Char(7 ),
  OM_CIDADE_COD Double(8,0),
  OM_TIPO_BATALHAO Varchar(3 ),
  OM_CGC Double(14,0),
  OM_CMDO_MIL_AREA_COD Varchar(6 ),
  CIDADE_PAIS_COD Double(4,0),
  NT_OM_DESCRICAO Varchar(50 ),
  OM_NOME_HISTORICO Varchar(50 ),
  OM_VM_DE_DESC Varchar(70 ),
  COMIL_A_SIGLA Varchar(30 ),
  PAIS_NOME_OFICIAL Varchar(50 ),
  OM_VM_DE_ORGAO_CODIGO Varchar(6 ),
  CIDADE_NOME Varchar(45 ),
  PAIS_PROCEDENCIA_MATERIAL Varchar(1 ),
  NAT_OM_CODIGO Double(2,0),
  PAIS_CODIGO_OTAN_PAIS Varchar(3 ),
  PAIS_PROCEDENCIA_EMPRESA Varchar(1 ),
  OM_VM_BDA_ORGAO_CODIGO Varchar(6 ),
  OM_VM_ORGAO_COD_SUBORD Varchar(6 ),
  PAIS_SIGLA Varchar(3 ),
  OM_CODIGO_UG Double(10,0),
  OM_REGIME Varchar(20 ),
  OM_RM_ORDEM Double,
  GP_OM_VAL_GRUPO_OM_COD Double(2,0),
  GP_OM_VAL_GRUPO_OM_DESC Varchar(50 ),
  GP_OM_VAL_GRUPO_OM_SIGLA Varchar(30 ),
  AUTONOMIA_ADMINISTRATIVA Varchar(4 ),
  BAIRRO Varchar(40 ),
  CEP Varchar(9 ),
  LOGRADOURO Varchar(70 ),
  DATA_SUBORDINACAO Date,
  NIVEL_SUBORDINACAO Varchar(4 ),
  DATA_ATRIBUICAO_CODOM Date,
  DESCRI_PORTARIA_ATRIBUIC_CODIG Varchar(100 ),
  DESCRI_PORTARIA_CRIACAO Varchar(100 ),
  DESCRI_PORTARIA_EXTINCAO Varchar(50 ),
  CAIXA_POSTAL Varchar(6 ),
  DESCRI_PORTARIA_SUBORDINACAO Varchar(100 ),
  DT_PORT_ATRIBUIC_CODOM Date,
  NR_PORTARIA_ATRIBUIC_CODOM Varchar(5 ),
  NR_PORTARIA_CRIACAO Varchar(6 ),
  NR_PORTARIA_EXTINCAO Double(5,0),
  NR_PORTARIA_SUBORDINACAO Varchar(5 ),
  ENCARGO_ENSINO Char(1 ),
  DIA_ANIVERSARIO Double(2,0),
  MES_ANIVERSARIO Double(2,0),
  NR_DOC_ATRIBUICAO_CODOM Varchar(5 ),
  DT_DOC_ATRIBUICAO_CODOM Date,
  DESCRI_DOC_ATRIBUICAO_CODOM Varchar(100 ),
  NR_DOC_SUBORDINACAO Varchar(5 ),
  DT_DOC_SUBORDINACAO Date,
  DESCRI_DOC_SUBORDINACAO Varchar(100 ),
  NR_DOC_EXTINCAO Double(5,0),
  DT_DOC_EXTINCAO Date,
  DESCRI_DOC_EXTINCAO Varchar(50 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Create indexes for table DIM_GEOGRAFIA

CREATE INDEX DIM_GEOGRAFIA_IDX_2 ON DIM_GEOGRAFIA (OM_DATA_EXTINCAO,OM_CMDO_MIL_AREA_COD)
;

CREATE INDEX DIM_GEOGRAFIA_IDX_3 ON DIM_GEOGRAFIA (OM_CODIGO_GUA,GP_OM_VAL_GRUPO_OM_COD,OM_DATA_EXTINCAO)
;

-- Add keys for table DIM_GEOGRAFIA

ALTER TABLE DIM_GEOGRAFIA ADD CONSTRAINT DIM_GEOGRAFIA_PK PRIMARY KEY (GEOGRAFIA_COD_SEQ)
;

ALTER TABLE DIM_GEOGRAFIA ADD CONSTRAINT DIM_GEOGRAFIA_UK UNIQUE (OM_CODIGO_GUA)
;


-- Table DIM_SITUACAO_MILITAR

CREATE TABLE DIM_SITUACAO_MILITAR(
  SITUACAO_MILITAR_COD Double(2,0),
  SITUACAO_MILITAR_DESC Varchar(30 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_SITUACAO_MILITAR

ALTER TABLE DIM_SITUACAO_MILITAR ADD CONSTRAINT DIM_SITUACAO_MILITAR_PK PRIMARY KEY (SITUACAO_MILITAR_COD)
;


-- Table DIM_DISPENSA_INCORP

CREATE TABLE DIM_DISPENSA_INCORP(
  DISPENSA_INCORP_COD Double(2,0),
  DISPENSA_INCORP_DESC Varchar(75 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_DISPENSA_INCORP

ALTER TABLE DIM_DISPENSA_INCORP ADD CONSTRAINT DIM_DISPENSA_INCORP_PK PRIMARY KEY (DISPENSA_INCORP_COD);
;


-- Table DIM_FORCA_DESEJA_SERVIR

CREATE TABLE DIM_FORCA_DESEJA_SERVIR(
  FORCA_DESEJA_SERVIR_COD Double(2,0),
  FORCA_DESEJA_SERVIR_DESC Varchar(30 ),
  DT_CARGA Timestamp(6),
  Attribute1 Varchar(42 )
);


-- Add keys for table DIM_FORCA_DESEJA_SERVIR

ALTER TABLE DIM_FORCA_DESEJA_SERVIR ADD CONSTRAINT DIM_FORCA_DESEJA_SERVIR_PK PRIMARY KEY (FORCA_DESEJA_SERVIR_COD)
;

  

-- Table DIM_CSE_INDICACAO

CREATE TABLE DIM_CSE_INDICACAO(
  CSE_INDICACAO_COD Double(2,0),
  CSE_INDICACAO_DESC Varchar(70),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 ) NOT NULL
);


-- Add keys for table DIM_CSE_INDICACAO

ALTER TABLE DIM_CSE_INDICACAO ADD CONSTRAINT DIM_CSE_INDICACAO_PK PRIMARY KEY (CSE_INDICACAO_COD)
;

-- Table DIM_CSE_RESULTADO

CREATE TABLE DIM_CSE_RESULTADO(
  CSE_RESULTADO_COD Double(2,0),
  CSE_RESULTADO_DESC Varchar(30),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_CSE_RESULTADO

ALTER TABLE DIM_CSE_RESULTADO ADD CONSTRAINT DIM_CSE_RESULTADO_PK PRIMARY KEY (CSE_RESULTADO_COD);
;

-- Table DIM_GRUPAM_INCORP

CREATE TABLE DIM_GRUPAM_INCORP(
  GRUPAM_INCORP_COD Varchar(1 ),
  GRUPAM_INCORP_DESC Varchar(30 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(30 )
);


-- Add keys for table DIM_GRUPAM_INCORP

ALTER TABLE DIM_GRUPAM_INCORP ADD CONSTRAINT DIM_GRUPAM_INCORP_PK PRIMARY KEY (GRUPAM_INCORP_COD)
;

-- Table DIM_DESTINO_MOBILIZACAO

CREATE TABLE DIM_DESTINO_MOBILIZACAO(
  DESTINO_MOB_COD Double(2,0),
  DESTINO_MOB_DESC Varchar(50),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_DESTINO_MOBILIZACAO

ALTER TABLE DIM_DESTINO_MOBILIZACAO ADD CONSTRAINT DIM_DESTINO_MOBIL_PK PRIMARY KEY (DESTINO_MOB_COD)
;

-- Table DIM_TIPO_DISTRIBUICAO

CREATE TABLE DIM_TIPO_DISTRIBUICAO(
  TIPO_DISTRIBUICAO_COD Double(2,0),
  TIPO_DISTRIBUICAO_DESC Varchar(30),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_TIPO_DISTRIBUICAO

ALTER TABLE DIM_TIPO_DISTRIBUICAO ADD CONSTRAINT DIM_TIPO_DISTRIBUICAO_PK PRIMARY KEY (TIPO_DISTRIBUICAO_COD)
;

-- Table DIM_SITUACAO_MOBILIZACAO

CREATE TABLE DIM_SITUACAO_MOBILIZACAO(
  SITUACAO_MOB_COD Double(2,0),
  SITUACAO_MOB_DESC Varchar(50),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42)
);


-- Add keys for table DIM_SITUACAO_MOBILIZACAO

ALTER TABLE DIM_SITUACAO_MOBILIZACAO ADD CONSTRAINT DIM_SITUACAO_MOB_PK PRIMARY KEY (SITUACAO_MOB_COD);
;

-- Table DIM_FORCA_MILITAR

CREATE TABLE DIM_FORCA_MILITAR(
  FORCA_MILITAR_COD Double(2,0),
  FORCA_MILITAR_DESC Varchar(30),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42)
);

-- Add keys for table DIM_FORCA_MILITAR

ALTER TABLE DIM_FORCA_MILITAR ADD CONSTRAINT DIM_FORCA_MILITAR_PK PRIMARY KEY (FORCA_MILITAR_COD);
;

-- Table DIM_GRUPO_DISTRIBUICAO

CREATE TABLE DIM_GRUPO_DISTRIBUICAO(
  GRUPO_DISTRIB_COD Double(2,0),
  GRUPO_DISTRIB_DESC Varchar(30 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(30 )
);


-- Add keys for table DIM_GRUPO_DISTRIBUICAO

ALTER TABLE DIM_GRUPO_DISTRIBUICAO ADD CONSTRAINT DIM_GRUPO_DISTRIBUICAO_PK PRIMARY KEY (GRUPO_DISTRIB_COD)
;


-- Table DIM_OCUPACAO

CREATE TABLE DIM_OCUPACAO(
  OCUPACAO_COD Varchar(5),
  OCUPACAO_DESC Varchar(30 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_OCUPACAO

ALTER TABLE DIM_OCUPACAO ADD CONSTRAINT DIM_OCUPACAO_PK PRIMARY KEY (OCUPACAO_COD);
;


-- Table DIM_CLASSE_RESERVA

CREATE TABLE DIM_CLASSE_RESERVA(
  CLASSE_RESERVA_COD Double(2,0),
  CLASSE_RESERVA_DESC Varchar(50 ),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42)
);

-- Add keys for table DIM_CLASSE_RESERVA

ALTER TABLE DIM_CLASSE_RESERVA ADD CONSTRAINT DIM_CLASSE_RESERVA_PK PRIMARY KEY (CLASSE_RESERVA_COD);
;


-- Table DIM_COMPORTAMENTO

CREATE TABLE DIM_COMPORTAMENTO(
  COMPORTAMENTO_COD Double(2,0),
  COMPORTAMENTO_DESC Varchar(30),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42)
);


-- Add keys for table DIM_COMPORTAMENTO

ALTER TABLE DIM_COMPORTAMENTO ADD CONSTRAINT DIM_COMPORTAMENTO_PK PRIMARY KEY (COMPORTAMENTO_COD);
;

-- Table DIM_JSM

CREATE TABLE DIM_JSM(
  CSM_COD Double(2,0),
  JSM_COD Double(3,0),
  CSM_DESC Varchar(40 ),
  CSM_SIGLA Varchar(10 ),
  JSM_DESC Varchar(70 ),
  JSM_TRIBUTACAO_COD Double(2,0),
  JSM_TRIBUTACAO_DESC Varchar(30 ),
  JSM_INFORMATIZADA_ST Varchar(2 ),
  MUNICIPIO_COD Double(8,0),
  MUNICIPIO_NOME Varchar(70 ),
  UF_SIGLA Varchar(2 ),
  UF_NOME Varchar(50 ),
  RM_SIGLA Varchar(30 ),
  RM_DESCRICAO Varchar(70 ),
  RM_CODIGO Varchar(6 ),
  RM_ORDEM Double(2,0),
  COMILA_CODIGO Varchar(6 ),
  COMILA_DESCRICAO Varchar(80 ),
  COMILA_SIGLA Varchar(30 ),
  DELSM_COD Double(3,0),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42 )
);


-- Add keys for table DIM_JSM

ALTER TABLE DIM_JSM ADD CONSTRAINT DIM_JSM_PK PRIMARY KEY (CSM_COD,JSM_COD);
;


-- Table DIM_ZONA_RESIDENCIAL

CREATE TABLE DIM_ZONA_RESIDENCIAL(
  ZONA_RESIDENCIAL_COD Double(2,0),
  ZONA_RESIDENCIAL_DESC Varchar(13),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42)
);


-- Add keys for table DIM_ZONA_RESIDENCIAL

ALTER TABLE DIM_ZONA_RESIDENCIAL ADD CONSTRAINT DIM_ZONA_RESIDENCIAL_PK PRIMARY KEY (ZONA_RESIDENCIAL_COD);
;


-- Table DIM_NIVEL_AJUSTAMENTO

CREATE TABLE DIM_NIVEL_AJUSTAMENTO(
  NIVEL_AJUSTAMENTO_COD Double(2,0),
  NIVEL_AJUSTAMENTO_DESC Varchar(30),
  DT_CARGA Timestamp(6),
  Attribute1 Varchar(42)
);


-- Add keys for table DIM_NIVEL_AJUSTAMENTO

ALTER TABLE DIM_NIVEL_AJUSTAMENTO ADD CONSTRAINT DIM_NIVEL_AJUSTAMENTO_PK PRIMARY KEY (NIVEL_AJUSTAMENTO_COD);
;



-- Table DIM_EVENTO_SERMIL

CREATE TABLE DIM_EVENTO_SERMIL(
  EVENTO_SERMIL_COD Double(2,0),
  EVENTO_SERMIL_DESC Varchar(50),
  DT_CARGA Timestamp(6),
  HASH_GERAL Varchar(42)
);


-- Add keys for table DIM_EVENTO_SERMIL

ALTER TABLE DIM_EVENTO_SERMIL ADD CONSTRAINT DIM_EVENTO_SERMIL_PK PRIMARY KEY (EVENTO_SERMIL_COD);
;


CREATE TABLE DIM_TEMPO_NG
   (  TEMPO_COD_SEQ DOUBLE NOT NULL, 
  DTEM_TRIMESTRE DOUBLE, 
  DTEM_DATA_FORMAT VARCHAR(35), 
  DTEM_DATA DATE, 
  DTEM_DT_FORMAT_HORA VARCHAR(35), 
  DTEM_QUINZENA DOUBLE, 
  DTEM_MES_EXTENSO VARCHAR(30), 
  DTEM_DIA_SEMANA VARCHAR(30), 
  DTEM_ANO DOUBLE, 
  DTEM_MES DOUBLE, 
  DTEM_DT_COMPLETA VARCHAR(35), 
  DTEM_AAAAMMDD DOUBLE, 
  DTEM_DIA DOUBLE, 
  DTEM_DT_ANOMES DOUBLE, 
  DTEM_DT_MES_EXTENSO VARCHAR(36), 
  DTEM_DT_ANOTRIMESTRE DOUBLE, 
  DTEM_DT_ANOSEMESTRE DOUBLE, 
  DTEM_DT_TRIMESTRE_EXTENSO VARCHAR(35), 
  DTEM_DT_SEMESTRE_EXTENSO VARCHAR(35), 
  DTEM_SEMESTRE DOUBLE, 
  DTEM_MES_ABREV VARCHAR(5), 
  DTEM_MES_ANO_ABREV VARCHAR(20), 
  DTEM_NRO_SEMANA DOUBLE(10) 

   );
  
  
  
  
  
CREATE TABLE DIM_MUNICIPIO
   (  MUNICIPIO_COD DOUBLE NOT NULL, 
  MUNICIPIO_NOME VARCHAR(70), 
  UF_SIGLA VARCHAR(2), 
  UF_NOME VARCHAR(50), 
  MUNICIPIO_SIGLA VARCHAR(5), 
  DT_CARGA TIMESTAMP, 
  HASH_GERAL VARCHAR(42)
   ) ;
  



-- Create relationships section ------------------------------------------------- 

ALTER TABLE FATO_EVENTO_CIDADAO ADD CONSTRAINT FATO_EVEN_JSM_FK FOREIGN KEY (CSM_COD, JSM_COD) REFERENCES DIM_JSM (CSM_COD, JSM_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_CLASS_RESV_FK FOREIGN KEY (CLASSE_RESERVA_COD) REFERENCES DIM_CLASSE_RESERVA (CLASSE_RESERVA_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_COMPORT_FK FOREIGN KEY (COMPORTAMENTO_COD) REFERENCES DIM_COMPORTAMENTO (COMPORTAMENTO_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_CSE_IND_FK FOREIGN KEY (CSE_INDICACAO_COD) REFERENCES DIM_CSE_INDICACAO (CSE_INDICACAO_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_CSE_RES_FK FOREIGN KEY (CSE_RESULTADO_COD) REFERENCES DIM_CSE_RESULTADO (CSE_RESULTADO_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_CSM_JSM_FK FOREIGN KEY (CSM_COD, JSM_COD) REFERENCES DIM_JSM (CSM_COD, JSM_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_DESTINO_MOB_FK FOREIGN KEY (DESTINO_MOB_COD) REFERENCES DIM_DESTINO_MOBILIZACAO (DESTINO_MOB_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_DISPENSA_FK FOREIGN KEY (DISPENSA_INCORP_COD) REFERENCES DIM_DISPENSA_INCORP (DISPENSA_INCORP_COD);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_ESCOLAR_FK FOREIGN KEY (ESCOLAR_COD_SEQ) REFERENCES DIM_ESCOLAR_NG (ESCOLAR_COD_SEQ);
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_FORC_DES_SV_FK FOREIGN KEY (FORCA_DESEJA_SERVIR_COD) REFERENCES DIM_FORCA_DESEJA_SERVIR (FORCA_DESEJA_SERVIR_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_FORC_MIL_FK FOREIGN KEY (FORCA_MILITAR_COD) REFERENCES DIM_FORCA_MILITAR (FORCA_MILITAR_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_GEOGRAFIA_FK FOREIGN KEY (GEOGRAFIA_COD_SEQ) REFERENCES DIM_GEOGRAFIA_NG (GEOGRAFIA_COD_SEQ)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_GRUPAM_INCORP_COD FOREIGN KEY (GRUPAM_INCORP_COD) REFERENCES DIM_GRUPAM_INCORP (GRUPAM_INCORP_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_GRUPO_DIST_FK FOREIGN KEY (GRUPO_DISTRIB_COD) REFERENCES DIM_GRUPO_DISTRIBUICAO (GRUPO_DISTRIB_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_MUN_NASC_FK FOREIGN KEY (MUNICIPIO_NASCIMENTO_COD) REFERENCES DIM_MUNICIPIO (MUNICIPIO_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_MUN_RESID_FK FOREIGN KEY (MUNICIPIO_RESIDENCIAL_COD) REFERENCES DIM_MUNICIPIO (MUNICIPIO_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_NIVEL_AJUST_FK FOREIGN KEY (NIVEL_AJUSTAMENTO_COD) REFERENCES DIM_NIVEL_AJUSTAMENTO (NIVEL_AJUSTAMENTO_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_OCUPACAO_FK FOREIGN KEY (OCUPACAO_COD) REFERENCES DIM_OCUPACAO (OCUPACAO_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_PAIS_NASC_FK FOREIGN KEY (PAIS_NASCIMENTO_COD) REFERENCES DIM_PAIS (CODIGO)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_PAIS_RESD_FK FOREIGN KEY (PAIS_RESIDENCIA_COD) REFERENCES DIM_PAIS (CODIGO)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_POSTO_FK FOREIGN KEY (POSTO_GRAD_COD_SEQ) REFERENCES DIM_POSTO_GRAD_ESPEC_NG (POSTO_GRAD_COD_SEQ)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_SIT_MILITAR_FK FOREIGN KEY (SITUACAO_MILITAR_COD) REFERENCES DIM_SITUACAO_MILITAR (SITUACAO_MILITAR_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_SIT_MOB_FK FOREIGN KEY (SITUACAO_MOB_COD) REFERENCES DIM_SITUACAO_MOBILIZACAO (SITUACAO_MOB_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_TP_DISTR_FK FOREIGN KEY (TIPO_DISTRIBUICAO_COD) REFERENCES DIM_TIPO_DISTRIBUICAO (TIPO_DISTRIBUICAO_COD)
;

ALTER TABLE DIM_CIDADAO ADD CONSTRAINT CIDADAO_ZONA_RESID_FK FOREIGN KEY (ZONA_RESIDENCIAL_COD) REFERENCES DIM_ZONA_RESIDENCIAL (ZONA_RESIDENCIAL_COD)
;

ALTER TABLE FATO_EVENTO_CIDADAO ADD CONSTRAINT FATO_EVEN_CIDADAO_FK FOREIGN KEY (CIDADAO_RA) REFERENCES DIM_CIDADAO (RA)
;

ALTER TABLE FATO_EVENTO_CIDADAO ADD CONSTRAINT FATO_EVEN_EVENTO_SERM_FK FOREIGN KEY (EVENTO_SERMIL_COD) REFERENCES DIM_EVENTO_SERMIL (EVENTO_SERMIL_COD)
;

ALTER TABLE FATO_EVENTO_CIDADAO ADD CONSTRAINT FATO_EVEN_GEOGRAFIA_FK FOREIGN KEY (GEOGRAFIA_COD_SEQ) REFERENCES DIM_GEOGRAFIA_NG (GEOGRAFIA_COD_SEQ)
;

ALTER TABLE FATO_EVENTO_CIDADAO ADD CONSTRAINT FATO_EVEN_CIDADAO_DIM_TEMPO_FK FOREIGN KEY (TEMPO_COD_SEQ) REFERENCES DIM_TEMPO_NG (TEMPO_COD_SEQ)
;



