drop table dim_classe_reserva;
CREATE EXTERNAL TABLE DIM_CLASSE_RESERVA(
  CLASSE_RESERVA_COD Double ,
  CLASSE_RESERVA_DESC Varchar(50 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
 PRIMARY KEY (CLASSE_RESERVA_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
location 'gs://svmil/classe_reserva'
tblproperties ("skip.header.line.count"="1")
;


-- row format delimited fields terminated by ','
-- ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' 
drop table DIM_COMPORTAMENTO;
CREATE EXTERNAL TABLE DIM_COMPORTAMENTO(
  COMPORTAMENTO_COD Double ,
  COMPORTAMENTO_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (COMPORTAMENTO_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/comportamento'
tblproperties ("skip.header.line.count"="1");


drop table DIM_CSE_INDICACAO;
CREATE EXTERNAL TABLE DIM_CSE_INDICACAO(
  CSE_INDICACAO_COD Double,
  CSE_INDICACAO_DESC Varchar(70 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ) ,
PRIMARY KEY ( CSE_INDICACAO_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/cse_indicacao'
tblproperties ("skip.header.line.count"="1");


drop table DIM_CSE_RESULTADO;
CREATE EXTERNAL TABLE DIM_CSE_RESULTADO(
  CSE_RESULTADO_COD Double,
  CSE_RESULTADO_DESC Varchar(30),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42),
 PRIMARY KEY (CSE_RESULTADO_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/cse_resultado'
tblproperties ("skip.header.line.count"="1");

--ALTER TABLE DIM_CSE_RESULTADO ADD PRIMARY KEY(CSE_RESULTADO_COD)


drop table DIM_DESTINO_MOBILIZACAO;
CREATE EXTERNAL TABLE DIM_DESTINO_MOBILIZACAO(
  DESTINO_MOB_COD Double,
  DESTINO_MOB_DESC Varchar(50 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (DESTINO_MOB_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/destino_mobilizacao'
tblproperties ("skip.header.line.count"="1")
;



drop table DIM_DISPENSA_INCORP;
CREATE EXTERNAL TABLE DIM_DISPENSA_INCORP(
  DISPENSA_INCORP_COD Double,
  DISPENSA_INCORP_DESC Varchar(75 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (DISPENSA_INCORP_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/dispensa_incop'
tblproperties ("skip.header.line.count"="1")
;



drop table dim_evento_sermil;
CREATE EXTERNAL TABLE DIM_EVENTO_SERMIL(
  EVENTO_SERMIL_COD Double,
  EVENTO_SERMIL_DESC Varchar(50 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY ( EVENTO_SERMIL_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/evento_sermil'
tblproperties ("skip.header.line.count"="1")
;


DROP TABLE DIM_FORCA_DESEJA_SERVIR;
CREATE EXTERNAL TABLE DIM_FORCA_DESEJA_SERVIR(
  FORCA_DESEJA_SERVIR_COD Double,
  FORCA_DESEJA_SERVIR_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  Attribute1 Varchar(42 ),
PRIMARY KEY ( FORCA_DESEJA_SERVIR_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/forca_deseja_servir'
tblproperties ("skip.header.line.count"="1")
;



DROP TABLE DIM_FORCA_MILITAR;
CREATE EXTERNAL TABLE DIM_FORCA_MILITAR(
  FORCA_MILITAR_COD Double,
  FORCA_MILITAR_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY ( FORCA_MILITAR_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/forca_militar'
tblproperties ("skip.header.line.count"="1")
;



DROP TABLE DIM_GEOGRAFIA;
CREATE EXTERNAL TABLE DIM_GEOGRAFIA(
  GEOGRAFIA_COD_SEQ Double,
  OM_DATA_EXTINCAO Date,
  OM_CODIGO_GUA Double,
  OM_SUBTIPO Varchar(20 ),
  RM_SIGLA Varchar(30 ),
  OM_VM_BDA_SIGLA Varchar(30 ),
  OM_SITUACAO Char(1 ),
  OM_SIGLA Varchar(30 ),
  PAIS_NOME Varchar(30 ),
  OM_PRIO Char(1 ),
  COMIL_A_DESCRICAO Varchar(80 ),
  OM_ORIGEM Varchar(20 ),
  PAIS_IPC Varchar(1 ),
  OM_TIPO_OP Varchar(70 ),
  OM_VM_SUBORDINADA_SIGLA Varchar(30 ),
  RM_DESCRICAO Varchar(70 ),
  OM_VM_RM_ORGAO_CODIGO Varchar(6 ),
  OM_DATA_CRIACAO Date,
  CIDADE_SIGLA Varchar(5 ),
  OM_TIPO Varchar(20 ),
  CIDADE_UF_COD Double,
  OM_CODOM Varchar(6 ),
  OM_VM_BDA_DESC Varchar(70 ),
  OM_VM_SUBORDINADA Varchar(70 ),
  UF_DESCRICAO Varchar(50 ),
  OM_NOME Varchar(70 ),
  CIDADE_TIPO_LOCAL Varchar(1 ),
  UF_SIGLA Varchar(2 ),
  OM_VM_DE_SIGLA Varchar(30 ),
  CIDADE_IBGE_MUNICIPIO_COD Char(7 ),
  OM_CIDADE_COD Double,
  OM_TIPO_BATALHAO Varchar(3 ),
  OM_CGC Double,
  OM_CMDO_MIL_AREA_COD Varchar(6 ),
  CIDADE_PAIS_COD Double,
  NT_OM_DESCRICAO Varchar(50 ),
  OM_NOME_HISTORICO Varchar(50 ),
  OM_VM_DE_DESC Varchar(70 ),
  COMIL_A_SIGLA Varchar(30 ),
  PAIS_NOME_OFICIAL Varchar(50 ),
  OM_VM_DE_ORGAO_CODIGO Varchar(6 ),
  CIDADE_NOME Varchar(45 ),
  PAIS_PROCEDENCIA_MATERIAL Varchar(1 ),
  NAT_OM_CODIGO Double,
  PAIS_CODIGO_OTAN_PAIS Varchar(3 ),
  PAIS_PROCEDENCIA_EMPRESA Varchar(1 ),
  OM_VM_BDA_ORGAO_CODIGO Varchar(6 ),
  OM_VM_ORGAO_COD_SUBORD Varchar(6 ),
  PAIS_SIGLA Varchar(3 ),
  OM_CODIGO_UG Double,
  OM_REGIME Varchar(20 ),
  OM_RM_ORDEM Double,
  GP_OM_VAL_GRUPO_OM_COD Double,
  GP_OM_VAL_GRUPO_OM_DESC Varchar(50 ),
  GP_OM_VAL_GRUPO_OM_SIGLA Varchar(30 ),
  AUTONOMIA_ADMINISTRATIVA Varchar(4 ),
  BAIRRO Varchar(40 ),
  CEP Varchar(9 ),
  LOGRADOURO Varchar(70 ),
  DATA_SUBORDINACAO Date,
  NIVEL_SUBORDINACAO Varchar(4 ),
  DATA_ATRIBUICAO_CODOM Date,
  DESCRI_PORTARIA_ATRIBUIC_CODIG Varchar(100 ),
  DESCRI_PORTARIA_CRIACAO Varchar(100 ),
  DESCRI_PORTARIA_EXTINCAO Varchar(50 ),
  CAIXA_POSTAL Varchar(6 ),
  DESCRI_PORTARIA_SUBORDINACAO Varchar(100 ),
  DT_PORT_ATRIBUIC_CODOM Date,
  NR_PORTARIA_ATRIBUIC_CODOM Varchar(5 ),
  NR_PORTARIA_CRIACAO Varchar(6 ),
  NR_PORTARIA_EXTINCAO Double,
  NR_PORTARIA_SUBORDINACAO Varchar(5 ),
  ENCARGO_ENSINO Char(1 ),
  DIA_ANIVERSARIO Double,
  MES_ANIVERSARIO Double,
  NR_DOC_ATRIBUICAO_CODOM Varchar(5 ),
  DT_DOC_ATRIBUICAO_CODOM Date,
  DESCRI_DOC_ATRIBUICAO_CODOM Varchar(100 ),
  NR_DOC_SUBORDINACAO Varchar(5 ),
  DT_DOC_SUBORDINACAO Date,
  DESCRI_DOC_SUBORDINACAO Varchar(100 ),
  NR_DOC_EXTINCAO Double,
  DT_DOC_EXTINCAO Date,
  DESCRI_DOC_EXTINCAO Varchar(50 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY ( GEOGRAFIA_COD_SEQ ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/geografia'
tblproperties ("skip.header.line.count"="1")
;






DROP TABLE DIM_GRUPAM_INCORP;
CREATE EXTERNAL TABLE DIM_GRUPAM_INCORP(
  GRUPAM_INCORP_COD Varchar(1),
  GRUPAM_INCORP_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(30 ),
PRIMARY KEY ( GRUPAM_INCORP_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/grupam_incorp'
tblproperties ("skip.header.line.count"="1")
;





DROP TABLE DIM_GRUPO_DISTRIBUICAO;
CREATE EXTERNAL TABLE DIM_GRUPO_DISTRIBUICAO(
  GRUPO_DISTRIB_COD Double,
  GRUPO_DISTRIB_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(30 ),
PRIMARY KEY ( GRUPO_DISTRIB_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/grupo_distrib'
tblproperties ("skip.header.line.count"="1")
;


DROP TABLE DIM_JSM;
CREATE EXTERNAL TABLE DIM_JSM(
  CSM_COD Double ,
  JSM_COD Double ,
  CSM_DESC Varchar(40 ),
  CSM_SIGLA Varchar(10 ),
  JSM_DESC Varchar(70 ),
  JSM_TRIBUTACAO_COD Double,
  JSM_TRIBUTACAO_DESC Varchar(30 ),
  JSM_INFORMATIZADA_ST Varchar(2 ),
  MUNICIPIO_COD Double,
  MUNICIPIO_NOME Varchar(70 ),
  UF_SIGLA Varchar(2 ),
  UF_NOME Varchar(50 ),
  RM_SIGLA Varchar(30 ),
  RM_DESCRICAO Varchar(70 ),
  RM_CODIGO Varchar(6 ),
  RM_ORDEM Double,
  COMILA_CODIGO Varchar(6 ),
  COMILA_DESCRICAO Varchar(80 ),
  COMILA_SIGLA Varchar(30 ),
  DELSM_COD Double,
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY ( CSM_COD, JSM_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/jsm'
tblproperties ("skip.header.line.count"="1")
;




DROP TABLE DIM_NIVEL_AJUSTAMENTO;
CREATE EXTERNAL TABLE DIM_NIVEL_AJUSTAMENTO(
  NIVEL_AJUSTAMENTO_COD Double ,
  NIVEL_AJUSTAMENTO_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  Attribute1 Varchar(42 ),
PRIMARY KEY (  NIVEL_AJUSTAMENTO_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/nivel_ajustamento'
tblproperties ("skip.header.line.count"="1")
;





DROP TABLE DIM_OCUPACAO;
CREATE EXTERNAL TABLE DIM_OCUPACAO(
  OCUPACAO_COD Varchar(5 ) ,
  OCUPACAO_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (OCUPACAO_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/ocupacao'
tblproperties ("skip.header.line.count"="1")
;






DROP TABLE DIM_SITUACAO_MILITAR;
CREATE EXTERNAL TABLE DIM_SITUACAO_MILITAR(
  SITUACAO_MILITAR_COD Double,
  SITUACAO_MILITAR_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (SITUACAO_MILITAR_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/sit_militar'
tblproperties ("skip.header.line.count"="1")
;



DROP TABLE DIM_SITUACAO_MOBILIZACAO;
CREATE EXTERNAL TABLE DIM_SITUACAO_MOBILIZACAO(
  SITUACAO_MOB_COD Double ,
  SITUACAO_MOB_DESC Varchar(50 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (SITUACAO_MOB_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/sit_mob'
tblproperties ("skip.header.line.count"="1")
;




DROP TABLE DIM_TIPO_DISTRIBUICAO;
CREATE EXTERNAL TABLE DIM_TIPO_DISTRIBUICAO(
  TIPO_DISTRIBUICAO_COD Double ,
  TIPO_DISTRIBUICAO_DESC Varchar(30 ),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (TIPO_DISTRIBUICAO_COD ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/tipo_distr'
tblproperties ("skip.header.line.count"="1")
;




DROP TABLE DIM_ZONA_RESIDENCIAL;
CREATE EXTERNAL TABLE DIM_ZONA_RESIDENCIAL(
  ZONA_RESIDENCIAL_COD Double,
  ZONA_RESIDENCIAL_DESC Varchar(13),
  DT_CARGA Timestamp,
  HASH_GERAL Varchar(42 ),
PRIMARY KEY (ZONA_RESIDENCIAL_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/zona_residencial'
tblproperties ("skip.header.line.count"="1")
;



DROP TABLE DIM_POSTO_GRAD_ESPEC_NG ;
 CREATE EXTERNAL TABLE DIM_POSTO_GRAD_ESPEC_NG ( 
POSTO_GRAD_COD_SEQ DOUBLE, 
POSTO_GRAD_CODIGO DOUBLE, 
POSTO_GRAD_PST_GRD_COD DOUBLE, 
PGRDSPC_COD_SUPERIOR DOUBLE, 
POSTO_GRAD_DESCRICAO VARCHAR(80), 
POSTO_GRAD_SIGLA VARCHAR(12), 
POSTO_GRAD_SUB_CIRC_COD DOUBLE, 
POSTO_GRAD_CIRC_DESC VARCHAR(80), 
COD_POSTO_SERMIL VARCHAR(2), 
DT_CARGA TIMESTAMP, 
HASH_GERAL VARCHAR(42), 
PRIMARY KEY (POSTO_GRAD_COD_SEQ) DISABLE NOVALIDATE) 
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/posto_grad'
tblproperties ("skip.header.line.count"="1")
;
   



drop table dim_tempo_ng;
CREATE EXTERNAL TABLE DIM_TEMPO_NG (
TEMPO_COD_SEQ DOUBLE , 
DTEM_TRIMESTRE DOUBLE, 
DTEM_DATA_FORMAT VARCHAR(35), 
DTEM_DATA DATE, 
DTEM_DT_FORMAT_HORA VARCHAR(35), 
DTEM_QUINZENA DOUBLE, 
DTEM_MES_EXTENSO VARCHAR(30), 
DTEM_DIA_SEMANA VARCHAR(30), 
DTEM_ANO DOUBLE, 
DTEM_MES DOUBLE, 
DTEM_DT_COMPLETA VARCHAR(35), 
DTEM_AAAAMMDD DOUBLE, 
DTEM_DIA DOUBLE, 
DTEM_DT_ANOMES DOUBLE, 
DTEM_DT_MES_EXTENSO VARCHAR(36), 
DTEM_DT_ANOTRIMESTRE DOUBLE, 
DTEM_DT_ANOSEMESTRE DOUBLE, 
DTEM_DT_TRIMESTRE_EXTENSO VARCHAR(35), 
DTEM_DT_SEMESTRE_EXTENSO VARCHAR(35), 
DTEM_SEMESTRE DOUBLE, 
DTEM_MES_ABREV VARCHAR(5), 
DTEM_MES_ANO_ABREV VARCHAR(20), 
DTEM_NRO_SEMANA DOUBLE ,
PRIMARY KEY (TEMPO_COD_SEQ ) DISABLE NOVALIDATE) 
  ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/tempo'
tblproperties ("skip.header.line.count"="1")
  ;
   
  
  
  drop table dim_municipio;  
CREATE EXTERNAL TABLE DIM_MUNICIPIO (
MUNICIPIO_COD DOUBLE , 
MUNICIPIO_NOME VARCHAR(70), 
UF_SIGLA VARCHAR(2), 
UF_NOME VARCHAR(50), 
MUNICIPIO_SIGLA VARCHAR(5), 
DT_CARGA TIMESTAMP, 
HASH_GERAL VARCHAR(42),
PRIMARY KEY (MUNICIPIO_COD) DISABLE NOVALIDATE) 
  ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/municipio'
tblproperties ("skip.header.line.count"="1")
  ;
   



drop table dim_cidadao;
CREATE EXTERNAL TABLE DIM_CIDADAO(
  RA double,
  MUNICIPIO_NASCIMENTO_COD double,
  PAIS_NASCIMENTO_COD double,
  ESTADO_CIVIL_COD double,
  ESTADO_CIVIL_DESC Varchar(30),
  SEXO_SG Char(1),
  ESCOLAR_COD_SEQ double,
  OCUPACAO_COD Varchar(5),
  SITUACAO_MILITAR_COD double,
  VINCULACAO_ANO double,
  ATUALIZACAO_DATA Date,
  ZONA_RESIDENCIAL_COD double,
  MUNICIPIO_RESIDENCIAL_COD double,
  PAIS_RESIDENCIA_COD double,
  CSM_COD double,
  JSM_COD double,
  DISPENSA_INCORP_COD double,
  TIPO_SANGUINEO Varchar(2),
  FATOR_RH Varchar(13),
  PESO double,
  ALTURA double,
  FORCA_MUSCULAR double,
  CABECA double,
  CALCADO_NR double,
  CINTURA_NR double,
  UNIFORME_NR Varchar(2),
  ACUIDADE_VISUAL_DESC Varchar(13 ),
  ACUIDADE_AUDITIVA_DESC Varchar(13 ),
  FORCA_DESEJA_SERVIR_COD double,
  SABE_NADAR_ST Char(1 ),
  CSE_INDICACAO_COD double,
  CSE_RESULTADO_COD double,
  GEOGRAFIA_COD_SEQ double,
  GRUPAM_INCORP_COD Varchar(1 ),
  PADRAO_CODIGO Varchar(3 ),
  TIPO_DISTRIBUICAO_COD double,
  NIVEL_AJUSTAMENTO_COD double,
  GRUPO_DISTRIB_COD double,
  DISTR_ORDEM_NR double,
  POSTO_GRAD_COD_SEQ double,
  QM_CODIGO Varchar(4 ),
  CARGO_MILITAR_CODIGO Varchar(4 ),
  QCP_FRACAO_ID Varchar(15 ),
  SITUACAO_MOB_COD double,
  DESTINO_MOB_COD double,
  CLASSE_RESERVA_COD double,
  COMPORTAMENTO_COD double,
  FORCA_MILITAR_COD double,
PRIMARY KEY (RA) DISABLE NOVALIDATE,
CONSTRAINT fk FOREIGN KEY (OCUPACAO_COD ) REFERENCES DIM_OCUPACAO(
  OCUPACAO_COD) DISABLE NOVALIDATE,
CONSTRAINT fk1 FOREIGN KEY ( SITUACAO_MILITAR_COD) REFERENCES DIM_SITUACAO_MILITAR(  SITUACAO_MILITAR_COD) DISABLE NOVALIDATE,
CONSTRAINT fk2 FOREIGN KEY ( ZONA_RESIDENCIAL_COD) REFERENCES DIM_ZONA_RESIDENCIAL(  ZONA_RESIDENCIAL_COD) DISABLE NOVALIDATE, 
CONSTRAINT fk3 FOREIGN KEY ( CSM_COD, JSM_COD) REFERENCES DIM_JSM(CSM_COD,JSM_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk4 FOREIGN KEY ( DISPENSA_INCORP_COD) REFERENCES DIM_DISPENSA_INCORP(DISPENSA_INCORP_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk5 FOREIGN KEY ( FORCA_DESEJA_SERVIR_COD ) REFERENCES DIM_FORCA_DESEJA_SERVIR(FORCA_DESEJA_SERVIR_COD ) DISABLE NOVALIDATE,  
CONSTRAINT fk6 FOREIGN KEY (CSE_INDICACAO_COD) REFERENCES DIM_CSE_INDICACAO(CSE_INDICACAO_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk7 FOREIGN KEY (CSE_RESULTADO_COD ) REFERENCES DIM_CSE_RESULTADO(CSE_RESULTADO_COD ) DISABLE NOVALIDATE,  
CONSTRAINT fk8 FOREIGN KEY (GEOGRAFIA_COD_SEQ  ) REFERENCES DIM_GEOGRAFIA(GEOGRAFIA_COD_SEQ ) DISABLE NOVALIDATE,  
CONSTRAINT fk9 FOREIGN KEY ( GRUPAM_INCORP_COD ) REFERENCES DIM_GRUPAM_INCORP(GRUPAM_INCORP_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk10 FOREIGN KEY (TIPO_DISTRIBUICAO_COD ) REFERENCES DIM_TIPO_DISTRIBUICAO(TIPO_DISTRIBUICAO_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk11 FOREIGN KEY (NIVEL_AJUSTAMENTO_COD) REFERENCES DIM_NIVEL_AJUSTAMENTO(NIVEL_AJUSTAMENTO_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk12 FOREIGN KEY (GRUPO_DISTRIB_COD) REFERENCES DIM_GRUPO_DISTRIBUICAO(GRUPO_DISTRIB_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk13 FOREIGN KEY (SITUACAO_MOB_COD ) REFERENCES DIM_SITUACAO_MOBILIZACAO(SITUACAO_MOB_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk14 FOREIGN KEY (DESTINO_MOB_COD) REFERENCES DIM_DESTINO_MOBILIZACAO(DESTINO_MOB_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk15 FOREIGN KEY (FORCA_MILITAR_COD) REFERENCES DIM_FORCA_MILITAR(FORCA_MILITAR_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk16 FOREIGN KEY (MUNICIPIO_RESIDENCIAL_COD) REFERENCES DIM_MUNICIPIO(MUNICIPIO_COD ) DISABLE NOVALIDATE,  
CONSTRAINT fk17 FOREIGN KEY (MUNICIPIO_NASCIMENTO_COD ) REFERENCES DIM_MUNICIPIO(MUNICIPIO_COD ) DISABLE NOVALIDATE,  
CONSTRAINT fk18 FOREIGN KEY (COMPORTAMENTO_COD) REFERENCES DIM_COMPORTAMENTO(COMPORTAMENTO_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk19 FOREIGN KEY (CLASSE_RESERVA_COD) REFERENCES DIM_CLASSE_RESERVA (CLASSE_RESERVA_COD) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/cidadao'
tblproperties ("skip.header.line.count"="1");



drop table FATO_EVENTO_CIDADAO;
CREATE EXTERNAL TABLE FATO_EVENTO_CIDADAO(
  CIDADAO_RA Double,
  EVENTO_SERMIL_COD Double,
  DT_EVENTO Date,
  CSM_COD Double,
  JSM_COD Double,
  GEOGRAFIA_COD_SEQ Double,
  CIDADAO_IDADE Double,
  ALTURA Double,
  ST_ADIAMENTO Char(1 ),
  TEMPO_COD_SEQ Double ,
  ANO_REFERENCIA Double ,
  PRIMARY KEY (CIDADAO_RA,EVENTO_SERMIL_COD,DT_EVENTO) DISABLE NOVALIDATE,
CONSTRAINT fk20 FOREIGN KEY ( CSM_COD,JSM_COD) REFERENCES DIM_JSM(CSM_COD,JSM_COD) DISABLE NOVALIDATE,  
CONSTRAINT fk21 FOREIGN KEY (CIDADAO_RA ) REFERENCES DIM_CIDADAO(RA) DISABLE NOVALIDATE,  
CONSTRAINT fk22 FOREIGN KEY (EVENTO_SERMIL_COD ) REFERENCES DIM_EVENTO_SERMIL(EVENTO_SERMIL_COD ) DISABLE NOVALIDATE,  
CONSTRAINT fk23 FOREIGN KEY (GEOGRAFIA_COD_SEQ  ) REFERENCES DIM_GEOGRAFIA(GEOGRAFIA_COD_SEQ ) DISABLE NOVALIDATE)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde' location 'gs://svmil/fato'
tblproperties ("skip.header.line.count"="1")
;  